### ISSUE TITLE
Missing values for "Area"

### ISSUE THREAD

**Issue by leberwurstsaft** [br1sk/Sonar#15]
It looks like there are many more cases in the bug reporter than there are in the app.

The list of values are (currently):

> Accelerate Framework, Accessibility, Accounts Framework, App Store, App Switcher, Audio, Audio Toolbox, AVFoundation, AVkit, Battery Life, Bluetooth, Calendar, CallKit, CarPlay, Cellular Service (Calls / Data), CFNetwork Framework, CloudKit, Contacts, Contacts Framework, Control Center, Core Animation, Core Bluetooth, Core Data, Core Foundation, Core Graphics, Core Image, Core Location, Core Media, Core Motion, Core Spotlight, Core Telephony Framework, Core Video, EventKit, External Accessory Framework, FaceTime, Foundation, GameplayKit, GLKit, Health App, HealthKit, Home App, Home Screen , HomeKit, iCloud, Image I/O, Intents Framework, IOKit, iPod Accessory Protocol (iAP), iTunes Connect, iTunes Store, Keyboard, Local Authentication Framework, Location Services, Lock Screen, Mail, MapKit, Maps, MDM, Media Player Framework, Messages, Messages Framework, Metal, Model I/O, Multipeer Connectivity Framework, Music, Network Extensions Framework, Notes, Notification Center, NotificationCenter Framework, Notifications, PassKit, Phone App, Photos, Photos Framework, Profiles, PushKit, QuickLook Framework, Reminders, ReplayKit, Safari, Safari Services, SceneKit, Security Framework, Setup Assistant, Simulator, Siri, Social Framework, Software Update, Spotlight, SpriteKit, StoreKit, System Slow/Unresponsive, SystemConfiguration Framework, TouchID, UIKit, UserNotifications Framework, VPN, Wallet, WebKit, Wi-Fi, Xcode, Something not on this list

**Comment by keith** [comment]
Thanks for reporting this, not sure how I missed it. It looks like there has been a change on the radar side (or we've always been doing it wrong) where the area codes are now dependent on the components. And components have different areas. And even thoughts that overlap, don't particularly correspond with an ID number. This seems a little bonkers, but I'm looking into a fix now.

**Comment by keith** [comment]
I've updated the data here: https://github.com/br1sk/Sonar/pull/17

**Comment by keith** [comment]
This is now fixed on master and being updated in Brisk shortly. Thanks for reporting it!

**Comment by leberwurstsaft** [comment]
Cool, thanks :)

**Comment by keith** [comment]
I've updated this in Brisk in the latest release https://github.com/br1sk/brisk/releases

Thanks again!
