### ISSUE TITLE
`productID` field

### ISSUE THREAD

**Issue by keith** [br1sk/Sonar#22]
It looks like the new radar (and possibly the old one too) provide a `productID` field in the creation body. In one of my tests with iOS & Accessibility as the product and area, this value was `210`. The component field also still exists. Inspecting the radar page, I don't see where this 210 value came from. I'm going to punt on this for now.

**Comment by ninjaprawn** [comment]
`productID` comes from each dictionary from the response from `https://bugreport.apple.com/developerUI/problem/getProductFullList`

**Comment by keith** [comment]
Any idea how that differs from the component?

**Comment by ninjaprawn** [comment]
As far as I know, nope.
